#!/usr/bin/env node

const { produce } = require('immer');
let data = {
    ids: [],
    map: {}
}
data = produce(data, draft => {
    let i = 0;
    while (process.env.HBU_TIMES > i) {
        draft.ids.push(i);
        draft.map[i] = {
            a: 1,
            b: 'Some data here'
        };
        i++;
    }
});
