#!/usr/bin/env node

const { produce } = require('immer');
const data = require('../../data');

const leak = [];

let i = 0;
while (process.env.HBU_TIMES > i) {
    leak.push(produce(data, () => {}));
    i++;
}
