#!/usr/bin/env node

const { mediary, realize } = require('../../..');
const data = require('../../data');

const leak = [];

let i = 0;
while (process.env.HBU_TIMES > i) {
    leak.push(realize(mediary(data)));
    i++;
}
