#!/usr/bin/env node

const data = require('../../data');
const { deepFreeze } = require('../../../util');
deepFreeze(data);

const leak = [];

let i = 0;
while (global.times > i) {
    leak.push(JSON.parse(JSON.stringify(data)));
    i++;
}
