#!/usr/bin/env node

const { produce } = require('immer');
const runner = require('./runner');
let data = {
    ids: [],
    map: {}
}
data = produce(data, draft => {
let i = 0;
while (global.times > i) {
    draft.ids.push(i);
    draft.map[i] = {
        a: 1,
        b: 'Some data here'
    };
    i++;
});
