#!/usr/bin/env node

const { mediary } = require('..');
const runner = require('./runner');
const data = require('./data');

const leak = [];

let i = 0;
while (global.times > i) {
    leak.push(mediary(data));
    i++;
}
