#!/usr/bin/env node

const mediary = require('..');
const runner = require('./runner');
const data = require('./data');

runner('mediary', 50000, x => {
    const merged = mediary(data).reduce((acc, v, i) => ({
        ...acc,
        ...v
    }), {});
    if (merged.oh[0] !== "A") throw new Error;
    if (merged.oh[1] !== "B") throw new Error;
    if (merged.oh[2] !== "C") throw new Error;
    if (merged.its.easy.as[0] !== 1) throw new Error;
    if (merged.its.easy.as[1] !== 2) throw new Error;
    if (merged.its.easy.as[2] !== 3) throw new Error;
    if (merged.as.simple.as[0] !== "do") throw new Error;
    if (merged.as.simple.as[1] !== "re") throw new Error;
    if (merged.as.simple.as[2] !== "mi") throw new Error;
    if (merged.baby.you.and[0] !== "me") throw new Error;
    if (merged.baby.you.and[1] !== "girl") throw new Error;
});
