#!/usr/bin/env node

const { mediary } = require('..');
const runner = require('./runner');
let data = {
    ids: [],
    map: {}
}

let i = 0;
while (global.times > i) {
    let cloned = mediary(data);
    cloned.ids.push(i);
    cloned.map[i] = {
        a: 1,
        b: 'Some data here'
    };
    data = cloned;
    i++;
}
