#!/usr/bin/env node

const testDir = 'tests';

const table = require('markdown-table')
const path = require('path');
const { spawnSync:spawn } = require('child_process');
const { readdirSync:readdir } = require('fs');

const run = testGroup => {
    console.log(`# ${testGroup.toUpperCase()}`);
    console.log(table([ [ 'Label', 'Heap Used', 'Elapsed Time' ], ...readdir(path.join(__dirname, testDir, testGroup)).map(name => JSON.parse(spawn('node', [ '-r', path.join(__dirname, './runner'), path.join(__dirname, testDir, testGroup, name), name, ...process.argv.slice(2) ]).stdout.toString())) ], { align: [ null, '.', '.' ] }), '\n');
};

run('incremental');
run('incremental-single');
run('leak');
run('read');
run('write');
