#!/usr/bin/env node

const runner = require('./runner');
const data = require('./data');
const cloned = JSON.parse(JSON.stringify(data));

runner('stringify', 100, x => {
    cloned.data.forEach(v => {
        v._id;
        v.index;
        v.guid;
        v.isActive;
        v.balance;
        v.picture;
        v.age;
        v.eyeColor;
        v.name;
        v.name.first;
        v.name.last;
        v.company;
        v.email;
        v.phone;
        v.address;
        v.about;
        v.registered;
        v.latitude;
        v.longitude;
        v.tags.forEach(v => v);
        v.range.forEach(v => v);
        v.friends.forEach(v => {
            v.id;
            v.name;
        });
        v.greeting;
        v.favoriteFruit;
    });
});
