#!/usr/bin/env node

const runner = require('./runner');
const data = require('./data');
const { deepFreeze } = require('../util');
deepFreeze(data);

const leak = [];

runner('stringify-create', 1000, x => {
    leak.push(JSON.parse(JSON.stringify(data)));
});
