#!/usr/bin/env node

const runner = require('./runner');
const data = require('./data');
const cloned = JSON.parse(JSON.stringify(data));

const leak = [];

runner('stringify-create', 1000, x => {
    leak.push(JSON.parse(JSON.stringify(data)));
});
