#!/usr/bin/env node

const { mediary } = require('../../..');
let data = {
    ids: [],
    map: {}
}

let i = 0;
while (process.env.HBU_TIMES > i) {
    let cloned = mediary(data);
    cloned.ids.push(i);
    cloned.map[i] = {
        a: 1,
        b: 'Some data here'
    };
    data = cloned;
    i++;
}
