#!/usr/bin/env node

const { produce } = require('../../..');
let data = {
    ids: [],
    map: {}
}

let i = 0;
while (global.times > i) {
    data = produce(data, cloned => {
        cloned.ids.push(i);
        cloned.map[i] = {
            a: 1,
            b: 'Some data here'
        };
    });
    i++;
}
